# ./docker-compose.test.yml
version: "3.9"

services:
  # THIS FIRST SERVICE, WE NEED DATBASE CONNECTION STRING HERE
  # OF A DATBASE WE WANT TO CONNECT
  # THIS IS A SERVICE OF A CONTAINER WHERE WE TEST OUR APP
  server:
    build:
      context: "."
      target: base
    environment:
      DATABASE_NAME: fancy-parrot
      DATABASE_URL: postgresql://themata:schism@localhost:5432/fancy-parrot
    ports:
      - 9999:80
    volumes:
      - ./src:/usr/src/app
      - ./package.json:/usr/src/app/package.json
    networks:
      - test_vm
    depends_on:
      - database

  # AS YOU CAN SEE THIS IS THE DATABASE SERVICE
  # SO THI REPRESENT OUR DATBASE THAT WE ARE GOING TO USE TO CONNECT
  # DURING TESTS
  database:
    image: postgres:13.3
    restart: always
    environment:
      - POSTGRES_USER=themata
      - POSTGRES_PASSWORD=schism
      - POSTGRES_DB=fancy-parrot
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - "54320:5432"
    networks:
      - test_vm

volumes:
  database:
networks:
  test_vm:
